
spring:
  application:
    name: calibrator-manager

  jpa:
    hibernate:
      ddl-auto: create-drop



  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.christiandellisanti.uk/realms/measurestream
